### ISSUE TITLE
Get GitHub API key

### ISSUE THREAD

**Issue by pedrogaudencio** [pedrogaudencio/gitbeep#6]
See [here](http://lmgtfy.com/?q=github+api+key).

**Comment by pedrogaudencio** [comment]
Ok, I have [one](https://help.github.com/articles/creating-an-access-token-for-command-line-use) now but I don't know how to use it... :disappointed:

Any idea, @PXke @jalavik @GRArmstrong?

**Comment by PXke** [comment]
What do you want to do with it ?

**Comment by pedrogaudencio** [comment]
Increase the amount of requests to the GitHub API...

**Comment by PXke** [comment]
I though we were already using one ? Do you want to mix keys to have more request ? If yes, that's sound :evil: :shipit:

**Comment by pedrogaudencio** [comment]
@PXke you fixed the requests' limit?
